/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Student */

#ifndef _Included_com_Student
#define _Included_com_Student
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Student
 * Method:    create_student
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_Student_create_1student
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_Student
 * Method:    print_student
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_Student_print_1student
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_Student
 * Method:    get_student_age
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_Student_get_1student_1age
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_Student
 * Method:    set_student
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_Student_set_1student
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
